version: 2
updates:
    - package-ecosystem: github-actions
      commit-message:
          include: scope
          prefix: ci
      cooldown:
          default-days: 7
      directory: /
      groups:
          github-owned:
              patterns:
                  - "actions/*"
                  - "github/*"
                  - "octokit/*"
      schedule:
          interval: monthly
