name: Plugin CI - Elasticsearch

on:
  workflow_call:
    inputs:
      auto-merge-exclude:
        description: 'A semicolon seperated list of packages that you do not want to be auto-merged.'
        required: false
        default: 'fastify'
        type: string
      elasticsearch-version:
        description: 'The version of Elasticsearch to use.'
        required: true
        default: '8.15.2'
        type: string
      license-check:
        description: 'Check licenses'
        required: false
        type: boolean
        default: false
      license-check-allowed-additional:
        description: 'A semicolon seperated list of additional licenses to allow.'
        required: false
        type: string
        default: ''
      lint:
        description: 'Set to true to run linting scripts.'
        required: false
        default: false
        type: boolean
      node-versions:
        description: 'A JSON array that specifies the Node.js versions on which the job should run.'
        required: false
        default: '["20", "22", "24"]'
        type: string

jobs:
  quality-check:
    uses: ./.github/workflows/plugins-ci-quality.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      license-check: ${{ inputs.license-check }}
      license-check-allowed-additional: ${{ inputs.license-check-allowed-additional }}
      lint: ${{ inputs.lint }}

  test:
    name: Node.js ${{ matrix.node-version }}
    needs: quality-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    services:
      elasticsearch:
        image: elasticsearch:${{ inputs.elasticsearch-version }}
        ports:
          - '9200:9200'
          - '9300:9300'
        env:
          xpack.security.enabled: false
          discovery.type: single-node
        options: >-
          --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: Run tests
        run: npm test

  automerge:
    name: Automerge Dependabot PRs
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'dependabot[bot]'
    needs: test
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@e820d631adb1d8ab16c3b93e5afe713450884a4a # v3.11.1
        with:
          exclude: ${{ inputs.auto-merge-exclude }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: major
